### ISSUE TITLE
Manifest unmarshal fails with service type

### ISSUE THREAD

**Issue by Gourab1998** [cloudfoundry-community/go-cfclient#392]
In Manifest schema, for services we have `type AppManifestService struct` array pointer as `Services`.
That works for `push operation` but when we try to unmarshal the response from generate function it fails with:

`
yaml: unmarshal errors:
  line 7: cannot unmarshal !!str xsuaa-tf into operation.AppManifestService
`  
Reason being cf controller changing services spec from object array to string array.

Example:-
cf push 

```yaml
applications:
- name: http-bin
  docker:
    image: kennethreitz/httpbin
  services:
  - name: xsuaa-tf
  processes:
  - type: web
    disk_quota: 1024M
    health-check-type: http
    health-check-http-endpoint: /get
    instances: 1
    memory: 256M
    readiness-health-check-type: http
    readiness-health-check-http-endpoint: /get
```

export GUID=$(cf app http-bin --guid)
cf curl "/v3/apps/$GUID/manifest"

```yaml
---
applications:
- name: http-bin
  docker:
    image: kennethreitz/httpbin
  services:
  - xsuaa-tf
  processes:
  - type: web
    instances: 1
    memory: 256M
    disk_quota: 1024M
    log-rate-limit-per-second: -1
    health-check-type: http
    health-check-http-endpoint: "/get"
    readiness-health-check-type: http
    readiness-health-check-http-endpoint: "/get"
```
